#baseURL = "https://illustratedman-code.github.io/GuideToCS/"
baseURL = "https://illustratedman-code.github.io/GuideToCS"
languageCode = "en-us"
title = "David Lewis's guide to CS"
theme = "docport"
canonifyURLs = true

[[menu.shortcuts]]
name = "Github"
url = "https://github.com/IllustratedMan-code"

[params]
    color_main = "#B0B0B0"
	color_second = "red"

[markup]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 2
