#+hugo_base_dir: ../
#+hugo_section: ecology
* Setup
+ no exams
+ groups of 4
+ group assignment in exam period
+ Read the entire textbook
+ 4 field-trips
+ august 31 lake
+ 9-14, 9-15 zoo
+ forest lab
+ october 26 UC field center
+ learning outcomes determine quiz questions.
* Chapter 1
:PROPERTIES:
:EXPORT_HUGO_SECTION*: ch1
:EXPORT_FILE_NAME: _index
:END:
** Terms
*** Ecology
The study of the interactions between an organism and its biological and physical environment.
*** Trait
A combination of characteristics in an individual. A trait that increases evolutionary fitness is an =adaptation=.
+ Hair color
+ resistance to antibiotics.
*** Population
All of the organisms of a particular species in a particular area.
+ The population of snow hares in the Himalayas.
*** Fitness
The degree to which an organism is likely to survive in an environment. The fitter the organism, the more likely they are to survive in an environment suited to their adaptations. This is more useful in the context of the population.
** Levels of Ecological organization
1. organism
2. population
3. community
4. ecosystem
** Proximate Vs Ultimate
*** Proximate Factors
Direct or Immediate causes/effects on the organism. The =How=.
+ Changes in photoperiod
+ Temperature changes
*** Ultimate Factors
The Indirect reason for an effect on the organism. The =Why=.

** Scientific Method and Hypothesis testing
Good hypothesis lead to testable =predictions=. It is also falsifiable.
1. Observation
2. Hypothesis
3. Measurements
4. Results
5. Conclusion
*** Predictions
A prediction is an observation or a result that is expected if the hypothesis is true.
*** Hypotheses and tests
+ Focus on a population
+ Why does the population exist?
+ What unique challenges does it face?
+ Are circumstances changing?
+ Will the population grow, shrink, disturbed
**** Resources
+ reproduction
+ Survival
+ Mate
+ Food
+ Shelter
* Chapter 2
:PROPERTIES:
:EXPORT_HUGO_SECTION*: ch-2
:EXPORT_FILE_NAME: _index
:END:
** review
1. mutation
2. allele
3. gene frequencies
4. genotype
5. phenotype
** Important terms for the course
+ =Evolution= is the change of populations (species) over time due to heritable changes.
+ =Natural Selection= is the "selection" of heritable traits due to their fitness
+ =Adaptation= is the tendency for natural selection to select changes most well suited to the environment.
+ =Fitness= is the likelihood that an organism will survive (pass its genes down) in its current environment.
** Mechanisms for evolutionary change
+ Natural Selection
+ Genetic drift
+ Gene Flow
+ Mutation pressure
** Natural section, genetic drift, gene flow
*** genetic drift
The random change of allele frequency based on non-random mating. Only affects populations with limited populations (non-random mating)
*** Gene flow
Individuals can move from population to population, or form a new population.
These fluctuations can change the allele frequencies in a population.
**** Isolation
Differentiation is affected by Isolation. Isolation prevents gene flow.
*** Hardy Weinberg
+ \(P^2 + 2PQ + Q^2\)
** Adaptation is an undirected process
Traits are not created to adapt to the environment. Traits instead are randomly generated (through mutation) and the traits that are well suited to the environment are selected for.
** Phenotypic Plasticity
Development of physiological variation among phenotypes induced directly by the environment.
+ Occurs during the development of an individual.
+ Himalayan Rabbits are a good example, they have areas of black fur if born in a cold environment.
** Adaptive landscape
An adaptive landscape is a three dimensional plot, where the x and y axis refer to allele frequency and the z axis refers to fitness. "Peaks" and "Valleys" show how different allele frequencies affect fitness and why genetic drift can be helpful for adaptation.
** Red Queen Hypothesis
Increased fitness in the short term does not always end well for the species.
This discrepancy of fitness between two related organisms (parasites/hosts, predators/prey) is related to generational rate. One of the species in the relationship cannot keep up evolutionarily with its pair species. This may result in extinction of prey or predator or both.
* Chapter 3
:PROPERTIES:
:EXPORT_HUGO_SECTION*: ch-3
:EXPORT_FILE_NAME: _index
:END:
** Adaptation to environmental factors
+ Change factors that limit growth (amount of food, composition of air)
+ Change Tolerance Range (Temperature tolerance, ph tolerance )
+ Change Behavior to adapt beyond Range ( avoid cold areas )
** Limiting environmental factors
+ physical factors (strength, ability to fly)
+ Physical resources
+ Tolerance bounds
** optimality and =Principle of allocation=
Adaptation to one challenge may decrease for another. The more an organism adapts to a stable environment (optimality), the less able it is to adapt to new environments that pose new challenges (moving from hot to cold, fresh water to salt water or vice versa)
+ Large beaks make it easier to break large nuts, but harder to eat insects out of trees.
+ Homeostasis allows humans to survive in a variety of environmental conditions, but requires more (is limited by) food.
** Normal Distribution and measures of variation
Many biological factors rely on modifications to the normal distribution.
+ quantified as a probability or confidence interval (95% of samples fall within this range of values)
+ \(\text{Sample Variance} = \frac{\sum_1^n (\bar x - x_i)^2}{n-1} = s^2\)
+ \(\text{Sample Mean} = \frac{\sum_1^n}{n} = \bar x\)
+ \(\text{confidence statistic (percentage)} = 1-\alpha\)
+ \(\text{confidence interval} = \bar x \pm t_{1-\alpha} * s/\sqrt n\)
+ \(\text{Standard Error (Estimate of the mean)} = \frac{s^2}{n}\)
*** Description of the plots used in ecology
+ y axis refers to the frequency of individuals (higher is more)
+ x axis refers to some limiting factor (food, temperature)
+ Peak refers to the mean of the sample
*** P Value
The P value is the probability that the Null hypothesis is true. This value is calculated with a statistical test (t test when using a sample).
**** Example
+ \(H_0 = \text{Cancer is randomly occuring}\)
+ \(H_a = \text{Cancer is caused by radiation damage}\)
+ \(P < 0.05\)
+ There is less than a 5 percent chance that cancer is randomly occurring.
